### ISSUE TITLE
重置选择文本颜色

### ISSUE THREAD

**Issue by rxliuli** [rxliuli/userjs#19]
ref: https://greasyfork.org/zh-CN/scripts/391193-%E8%A7%A3%E9%99%A4%E7%BD%91%E9%A1%B5%E9%99%90%E5%88%B6/discussions/77926#comment-196184

另外建议检查一下该网址：boke112.com，使用脚本之后仍无法解除限制，谢谢

**Comment by rxliuli** [comment]
吾辈猜测应该是修改了选中文本的颜色
![image](https://user-images.githubusercontent.com/24560368/114290147-faa4f100-9aaf-11eb-9ca2-ea17a42e2b29.png)

而且只在部分网址生效
https://boke112.com/post/9100.html

**Comment by rxliuli** [comment]
应该解决选择文本之后 C-C 并未复制的错误，而选中文本颜色没有高亮的问题则应考虑使用其他选项

**Comment by rxliuli** [comment]
你可以先使用 user style 恢复文本高亮的颜色

```css
/* ==UserStyle==
@name           boke112 选中文本颜色恢复高亮
@namespace      github.com/openstyles/stylus
@version        1.0.0
@description    A new userstyle
@author         Me
==/UserStyle== */

@-moz-document domain("boke112.com") {
    /* 在此插入代码... */
    :not(input):not(textarea)::selection {
        color: white !important;
        background-color: #05d3f9 !important;
    }
}
```

选中之后右键复制即可 @shenzhiming88
