### ISSUE TITLE
部分网页使用透明遮罩层防止选择

### ISSUE THREAD

**Issue by DeepChirp** [rxliuli/userjs#27]
示例：https://votetw.com/wiki/%E6%9E%97%E6%99%BA%E5%A0%85
该网页加了透明遮罩层防止复制，并没有通过监听事件的方式限制。不知道能否针对此种方式优化一下（不过我觉得可能会有误伤）
![动画](https://user-images.githubusercontent.com/66902050/115132144-33a11080-a030-11eb-9baf-695efdd5820a.gif)

**Comment by rxliuli** [comment]
这个考虑了一下还是不太方便全局支持，你可以使用下面的 user.css 删除该遮罩

```css
/* ==UserStyle==
@name           votetw.com 删除遮罩层
@namespace      github.com/openstyles/stylus
@version        1.0.0
@description    A new userstyle
@author         rxliuli
==/UserStyle== */

@-moz-document domain("votetw.com") {
    div[style*="width: 100%; height: 100%; top: 0;left: 0; position:fixed; z-index: 255;"] {
        display: none;
    }
}
```

> [user.css 插件](https://chrome.google.com/webstore/detail/stylus/clngdbkpkpeebahjckkjfobafhncgmne?hl=de)
